apiVersion: v1
kind: Pod
metadata:
  name: my-pod
spec:
  containers:
    - name: mongo
      image: mongo:latest
      startupProbe:
        tcpSocket:
          port: 27017
        periodSeconds: 1
        failureThreshold: 3

