#nginx will start after 10 seconds
#To simulate the liveness probe failing, enter the container and rm /usr/share/nginx/html/live.html
apiVersion: v1
kind: Pod
metadata:
  name: my-pod
spec:
  terminationGracePeriodSeconds: 1
  containers:
    - name: probe-demo
      image: vinsdocker/k8s-probe-demo
      startupProbe:
        httpGet:
          path: /
          port: 80
        periodSeconds: 1
        failureThreshold: 30
      livenessProbe:
        httpGet:
          path: /live.html
          port: 80
        #for live scenarios, it's better to have a higher periodSeconds
        periodSeconds: 1
        failureThreshold: 3

