apiVersion: v1
kind: Secret
metadata:
  name: app-secret
data:
  #values need to be base64 encoded
  username: dmlub3Ro
  password: YWRtaW4xMjM=
---
apiVersion: v1
kind: Pod
metadata:
  name: my-pod
spec:
  restartPolicy: Never
  containers:
  - name: ubuntu
    image: ubuntu
    envFrom:
    - secretRef:
        name: app-secret
    args:
    - env