apiVersion: apps/v1
kind: Deployment # Extends ReplicaSet
metadata:
  name: my-deploy
spec:
  selector:
    matchLabels:
      app: my-app
      colour: red
  replicas: 2
  template:
    metadata:
      name: my-pod
      labels:
        app: my-app
        colour: red
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
