apiVersion: v1
kind: Pod
metadata:
    name: my-pod
spec:
    containers:
    - name: my-simple-container
      image: nginx:latest
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
