apiVersion: v1
kind: Pod
metadata:
  name: pod-1
  labels:
    team: dev
    colour: blue
spec:
  containers:
  - name: my-simple-container
    image: nginx:latest
    ports:
    - containerPort: 80
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-2
  labels:
    team: dev
    colour: blue
spec:
  containers:
  - name: my-simple-container
    image: nginx:latest
    ports:
    - containerPort: 80
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"

