apiVersion: v1
kind: Pod
metadata:
  name: pod-1
spec:
  restartPolicy: Never # Always, OnFailure, Never
  containers:
  - name: ubuntu
    image: ubuntu
    args:
    - "/bin/sh"
    - "-c"
    - "echo this is the path $PATH"

    resources:
      limits:
        memory: "512Mi"
        cpu: "500m"
