apiVersion: v1
kind: Pod
metadata:
  name: pod-1
spec:
  restartPolicy: Never # Always, OnFailure, Never
  terminationGracePeriodSeconds: 2
  containers:
  - name: ubuntu
    image: ubuntu
    args:
    - "sleep"
    - "3600"
    resources:
      limits:
        memory: "512Mi"
        cpu: "500m"
