apiVersion: v1
kind: Pod
metadata:
    name: my-pod
spec:
    containers:
    - name: my-simple-container
      image: ubuntu
      env:
        - name: "request.timeout"
          value: "30"
      args:
        - "env"
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"


