apiVersion: v1
kind: Pod
metadata:
    name: my-pod
spec:
    restartPolicy: Never
    terminationGracePeriodSeconds: 1
    containers:
    - name: nginx1
      image: nginx
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
    # - name: nginx2
    #   image: nginx
    #   #set nginx port to another one
    #   env:
    #   - name: NGINX_PORT
    #     value: "8082"
    #   resources:
    #     limits:
    #       memory: "128Mi"
    #       cpu: "500m"
    - name: util
      image: vinsdocker/util
      args:
        - "sleep"
        - "3600"
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"


