apiVersion: apps/v1
kind: Deployment # Extends ReplicaSet
metadata:
  name: order-service-deploy
spec:
  selector:
    matchLabels:
      app: order-service
  replicas: 2
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
      - name: order-service
        image: vinsdocker/k8s-app:v2
        ports:
          - name: https
            containerPort: 80
        env:
          - name: APP_ENV
            value: "dev"