apiVersion: apps/v1
kind: Deployment # Extends ReplicaSet
metadata:
  name: order-service-deploy
  annotations:
    kubernetes.io/change-cause: "Deploying v3"
spec:
  selector:
    matchLabels:
      app: order-service
  replicas: 2
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
      - name: order-service
        image: vinsdocker/k8s-app:v3
        ports:
          - name: https
            containerPort: 80
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"