apiVersion: apps/v1
kind: Deployment # Extends ReplicaSet
metadata:
  name: order-service-deploy
spec:
  minReadySeconds: 10
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: order-service
  replicas: 3
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
      - name: order-service
        image: vinsdocker/k8s-app:v2
        ports:
          - name: https
            containerPort: 80
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"