apiVersion: v1
kind: Pod
metadata:
  name: my-pod-1
  labels:
      team: team-a
spec:
  containers:
  - name: my-simple-container
    image: nginx:latest
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
---
apiVersion: v1
kind: Pod
metadata:
    name: my-pod-2
    labels:
        team: team-a
spec:
  containers:
  - name: my-simple-container
    image: nginx:latest
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
---
apiVersion: v1
kind: Pod
metadata:
  name: my-pod-3
  labels:
    team: team-a
spec:
  containers:
  - name: my-simple-container
    image: nginx:latest
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"