kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: dev-cluster
nodes:
  - role: control-plane
    #This will map the container port 80 to the host port 30001
    extraPortMappings:
    - containerPort: 30001
      hostPort: 30001
      protocol: TCP
  - role: worker
  - role: worker

#